config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  root "users#index"

  # Posts Routes
  get 'users/:user_id/posts', to: 'posts#index', as: :posts
  get 'users/:user_id/posts/:id', to: 'posts#show', as: :post

  # Users Routes
  get 'users/', to: 'users#index'
  get 'users/:id', to: 'users#show', as: :user

  # New Posts Route
  get 'posts/new', to: 'posts#new', as: :new_post

  # Post routes
  post 'posts/new', to: 'posts#create'
  post 'users/:user_id/posts/:id', to: 'comments#create', as: :comment
  post 'users/:user_id/posts/:id/likes', to: 'likes#create', as: :like
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end

  private :update_comments_counter
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end

  private :update_likes_counter
end

app/models/post.rb
class Post < ApplicationRecord
  # Data Relationships
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  # Data Validation
  validates :title, presence: true, length: { in: 1..250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_save :update_posts_counter

  def recent_comments
    Comment.where(post: self).order(updated_at: :desc).first(5)
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  private :update_posts_counter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :validatable

  # Data Relationships
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  # Data Validation
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_posts
    Post.where(author: self).order(updated_at: :desc).first(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  def create
    @current_user = current_user
    @current_post = Post.find(params[:id])
    @comment = Comment.new(comment_params)
    @comment.author = @current_user
    @comment.post = @current_post

    if @comment.save
      flash[:success] = 'Your comment was saved!'
      redirect_to post_path(@current_user.id)
    else
      flash.now[:error] = 'Error: Comment was not saved'
    end
  end

  def comment_params
    params.require(:comment).permit(:author, :post, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @current_user = current_user
    @current_post = Post.find(params[:id])
    @comment = Comment.new(comment_params)
    @comment.author = @current_user
    @comment.post = @current_post

    if @comment.save
      flash[:success] = 'Your comment was saved!'
      redirect_to post_path(@current_user.id)
    else
      flash.now[:error] = 'Error: Comment was not saved'
    end
  end

  def comment_params
    params.require(:comment).permit(:author, :post, :text)
  end
end

app/controllers/like_controller.rb
class LikesController < ApplicationController
  def create
    @current_user = current_user
    @current_post = Post.find(params[:id])
    @like = Like.new
    @like.author = @current_user
    @like.post = @current_post

    if @like.save
      flash[:success] = 'Your like was added!'
      redirect_to post_path(@current_user.id)
    else
      flash.now[:error] = 'Error: Like was not added'
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @current_user = current_user
    @current_post = Post.find(params[:id])
    @like = Like.new
    @like.author = @current_user
    @like.post = @current_post

    if @like.save
      flash[:success] = 'Your like was added!'
      redirect_to post_path(@current_user.id)
    else
      flash.now[:error] = 'Error: Like was not added'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @users = User.all
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id])
    @comments = Comment.all.includes([:post])
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
    @comments = Comment.where(post_id: params[:id]).includes([:post])
    @users = User.all
  end

  def new
    @current_user = current_user
    @post = Post.new
  end

  def create
    @current_user = current_user
    @post = @current_user.posts.create(post_params)

    if @post.save
      redirect_to posts_path(@current_user.id)
      flash[:success] = 'Your post was save!'
    else
      flash.now[:error] = 'Error: Your post was not saved!'
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(author_id: params[:id]).order(updated_at: :desc).first(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Blog App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  
  <!-- Bootstrap Styles and Scripts -->
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  
  <!-- My Styles -->
  <%= stylesheet_link_tag "application", "users", "posts", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <header class="d-flex justify-content-center">
    <h1>Welcome to the Blog App</h1>
  </header>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <section id="main-container" class="container d-flex flex-column justify-content-center align-items-center">
    <%= yield %>
  </section>
</body>
</html>

app/views/posts/index.html.erb
<main>
  <section class="users-section d-flex justify-content-center flex-column align-items-center">
    <article class="users-info">
      <div class="users-section-card d-flex">
        <img src="<%= @user.photo %>">
        <h4><%= @user.name %></h4>
        <p>Number of Posts: <%= @user.posts_counter %></p>
      </div>
    </article>

    <% @posts.each do |post| %>
      <article class="users-posts">
          <div class="post-card">
            <%= link_to post_path(post.author_id, post.id) do %>
              <h3>Post #<%= post.id %>: <%= post.title %></h3>
            <% end %>
            <p class="post-card-d"><%= post.text %></p>
            <p class="post-card-a">
              Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
            </p>
          </div>

        <div class="posts-comments">
          <% @comments.each do |comment| %>
            <% if post.id == comment.post.id %>
              <p class="comment-d"><%= @users[comment.author_id].name %>: <%= comment.text %></p>
            <% end %>
          <% end %>
        </div>
      </article>
    <% end %>

    <div class="posts-btns">
      <%= link_to new_post_path do %>
        <button>Add a new post</button>
      <% end %>

      <%= link_to user_path(@user.id) do %>
        <button>Go back</button>
      <% end %>

      <%= link_to users_path do %>
        <button>Main Page</button>
      <% end %>
    </div>
  </section>
</main>

app/views/posts/new.html.erb
<h3>Add your new post!</h3>

<%= form_with model: @post, url: new_post_path, method: :post, scope: :post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  <%= form.submit :'Create Post' %>
<% end %>

app/views/posts/show.html.erb
<main>
  <section class="user-section d-flex justify-content-center flex-column align-items-center">
    <article class="user-posts">
      <div class="posts-header">
        <h2><%= @post.title %> by <%= @user.name %></h2>
        <div class='like_button'>
          <%= form_with url: like_url(@current_user), method: :post do |form| %>
            <% form.submit 'Like' %>
          <% end %>
        </div>
      </div>

      <p class="post-card-a">
        Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %>
      </p>
      <p><%= @post.text %></p>

      <%= form_with url: post_url(@user, @post), method: :post, local: true, scope: :comment do |form| %>      
        <div>
          <%= form.label :text %>
          <%= form.text_field :text %>
        </div>
        <%= form.submit :'Create Comment' %>
      <% end %>
    </article>

    <div class="posts-comments">
      <% @comments.each do |comment| %>
        <% if @post.id == comment.post.id %>
          <p class="comment-d"><%= @users[comment.author_id].name %>: <%= comment.text %></p>
        <% end %>
      <% end %>
    </div>

    <%= link_to "Back to Posts", posts_path(@user.id)%>
  </section>
</main>

app/views/users/index.html.erb
<main>
  <section class="users-container d-flex justify-content-center flex-column align-items-center">
    <% if @users.empty? %>
      <h2>There are no users in the database</h2>
    <% else %>
      <h2>Take a look at all of the users and their number of posts</h2>

      <% @users.each do |user| %>
        <article class="users-section d-flex justify-content-center align-items-center">
          <img src="<%= user.photo %>">

          <%= link_to user_path(user.id) do %>
            <div class="users-section-card d-flex">
              <h4><%= user.name %></h4>
              <p>Number of Posts: <%= user.posts_counter %></p>
            </div>
          <% end %>
        </article>
      <% end %>

    <% end %>
  </section>
</main>

app/views/users/show.html.erb
<main>
  <section class="users-section d-flex justify-content-center flex-column align-items-center">
    <article class="users-info">
      <div class="users-section-card d-flex">
        <img src="<%= @user.photo %>">

        <h4><%= @user.name %></h4>
        <p>Number of Posts: <%= @user.posts_counter %></p>
      </div>
    </article>

    <article class="users-bio">
      <p><%= @user.bio %></p>
    </article>

    <article class="users-posts">
      <% if @posts.empty? %>
        <p>There are no posts for this user</p>
      <% else %>
        <% @posts.each do |post| %>
          <div class="post-card">
            <h3>Post #<%= post.id %>: <%= post.title %></h2>
            <p class="post-card-d"><%= post.text %></p>
            <p class="post-card-a">
              Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
            </p>
          </div>
        <% end %>
      <% end %>
    </article>

    <div class="posts-btns">
      <%= link_to posts_path(@user.id) do %>
        <button>See all posts</button>
      <% end %>

      <%= link_to new_post_path do %>
        <button>Add a new post</button>
      <% end %>

      <%= link_to users_path do %>
        <button>Main Page</button>
      <% end %>
    </div>
  </section>
</main>